name: "bluebell"
mode: "dev"
port: 8080
version: "v0.0.1"
start_time: "2000-09-12"
machine_id: 1

log:
  level: "debug"
  filename: "web_app.log"
  max_size: 200   #大小
  max_age: 30     #储存天数
  max_backups: 7  #备份数量

mysql:
  host: "localhost"
  port: 3306
  user: "root"
  password: "123456"
  dbname: "bluebell"
  max_open_conns: 200
  max_idle_conns: 50

redis:
  host: "localhost"
  port: 6379
  password: ""
  db: 0
  pool_size: 100

